name: Build EXE on Push

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the build

jobs:
  build:
    runs-on: windows-latest  # Required for building Windows executables

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'  # Adjust this based on your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed DOC_Analyzer.py  # Change to your main script filename

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-exe
          path: dist/DOC-Analyzer.exe  # Change to match your script name

      - name: Release EXE (optional)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          files: dist/DOC-Analyzer.exe
          tag_name: latest
          name: Latest Build
          draft: false
          prerelease: false
