name: Build EXE and Create ZIP

on:
  push:
    branches:
      - master  # Change this to the branch you want to trigger the build
      

permissions:
  contents: write  # This gives permission to create releases

jobs:
  build:
    runs-on: windows-latest  # Required for building Windows executables

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: da-env
          environment-file: environment.yml

      - name: Install dependencies from environment.yml
        run: |
          conda env update --file environment.yml --name da-env
          conda activate da-env
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --clean --name DocAnalyzer --add-data "modules;modules" --add-data "modules/Sahel.ttf;modules" DOC_Analyzer.py

      - name: Create ZIP File
        run: |
          powershell Compress-Archive -Path dist\DocAnalyzer.exe, ReadMe.txt , Update_App.bat -DestinationPath dist\DocAnalyzer_windows.zip

      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyCustomApp-ZIP
          path: dist/DocAnalyzer_windows.zip

      - name: Create Release and Upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: dist/DocAnalyzer_windows.zip
          tag_name: latest
          name: Latest Build
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
